### ISSUE TITLE
Finer Points of F# Value Restriction

### ISSUE THREAD

**Issue by ForNeVeR** [fsharplang-ru/translations#15]
https://blogs.msdn.microsoft.com/mulambda/2010/05/01/finer-points-of-f-value-restriction/

Лицензия: запрашиваю у автора в комментариях.

**Comment by Neftedollar** [comment]
Это очень интересная статья

**Comment by ForNeVeR** [comment]
Автор дал нам разрешение на перевод:
![image](https://cloud.githubusercontent.com/assets/92793/26620933/0a621432-460f-11e7-9b00-26f9a1598262.png)

**Comment by AnnaUdovichenko** [comment]
Я готова рискнуть с переводом этой статьи.
