### ISSUE TITLE
Get Started with F# as a C# developer

### ISSUE THREAD

**Issue by gsomix** [fsharplang-ru/translations#17]
https://blogs.msdn.microsoft.com/dotnet/2017/07/24/get-started-with-f-as-a-c-developer/

Лицензия:

> gsomix
> Hello, Phillip. My name is Evgeniy Andreev, I'm member of the Russian-speaking F# community. Do you mind if I translate your article "Get Started with F# as a C# developer" into Russian? What's license status of MSDN blog posts? We plan to publish translations on a website (fsharplang-ru.github.io) keeping links to original articles. Thanks in advance!
> ...
>cartermp
> Good news!  Feel free to translate and post it on your site.  We just require that you link to it and say that this is a translated version :)

**Comment by FoggyFinder** [comment]
Сам хотел предложить для перевода =)
