### ISSUE TITLE
Fork fsharpforfunandprofit.com

### ISSUE THREAD

**Issue by kleidemos** [fsharplang-ru/translations#32]
Я добиваю свой перевод #3 (не прошло и года), Мне кажется сообществу стоит сделать форк https://github.com/swlaschin/fsharpforfunandprofit.com, чтобы не заморачиваться со ссылками и т.п. Авось со временем подъедут и другие серии.

// Как поддерживать обновления без понятия.

**Comment by ForNeVeR** [comment]
Вроде бы форкнули сюда: https://github.com/fsharplang-ru/fsharpforfunandprofit.gitbook
